### ISSUE TITLE
how can i fixed 

### ISSUE THREAD

**Issue by chenjia1949** [googleapis/java-analytics-data#372]
QuickstartSample 
Exception in thread "main" java.lang.NoSuchMethodError: com.google.analytics.data.v1beta.stub.BetaAnalyticsDataStubSettings$Builder.setMtlsEndpoint(Ljava/lang/String;)Lcom/google/api/gax/rpc/StubSettings$Builder;
        at com.google.analytics.data.v1beta.stub.BetaAnalyticsDataStubSettings$Builder.createDefault(BetaAnalyticsDataStubSettings.java:331)
        at com.google.analytics.data.v1beta.stub.BetaAnalyticsDataStubSettings$Builder.access$000(BetaAnalyticsDataStubSettings.java:225)
        at com.google.analytics.data.v1beta.stub.BetaAnalyticsDataStubSettings.newBuilder(BetaAnalyticsDataStubSettings.java:200)
        at com.google.analytics.data.v1beta.BetaAnalyticsDataSettings$Builder.createDefault(BetaAnalyticsDataSettings.java:181)
        at com.google.analytics.data.v1beta.BetaAnalyticsDataSettings$Builder.access$000(BetaAnalyticsDataSettings.java:162)
        at com.google.analytics.data.v1beta.BetaAnalyticsDataSettings.newBuilder(BetaAnalyticsDataSettings.java:144)
        at com.qiyee.job.msg.QuickstartSample.sampleRunReport(QuickstartSample.java:41)
        at com.qiyee.job.msg.QuickstartSample.main(QuickstartSample.java:28)

**Comment by chanseokoh** [comment]
I suggest you [use a BOM](https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM) to eliminate such a runtime classpath issue.

> Google maintains several foundation libraries that can be used for very general purposes, which the GCP libraries also depend on. When we publish a version of Google Cloud Platform Libraries BOM, we ensure that the libraries in the BOM do not have dependency conflicts, that would manifest as `NoSuchMethodError` or `NoClassDefFoundError`. By using the Libraries BOM, you can ensure your projects always have compatible versions of these several hundred different artifacts.

Going to close it, but feel free to update.
